4 create crud for users
nguyenhoanganhtuan1206/Java-Template pull request #4
Opened 2023-03-06 02:04 UTC by nguyenhoanganhtuan1206

4 create crud for users

2023-03-06 02:13 UTC, tleviet commented on src/main/java/com/javatemplate/api/user/UserController.java
> +public class UserController {
Mình có api search user theo name ko e?
cc @voquanghoa

2023-03-06 02:14 UTC, tleviet commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        System.out.println("user" + user.getUsername());
xoá dòng này nếu ko dùng e?

2023-03-06 02:16 UTC, tleviet commented on src/main/java/com/javatemplate/error/UserExistedException.java
> +public class UserExistedException extends DomainException {
Nên dùng class name `UserAlreadyExistsException` e

2023-03-06 02:20 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("select u from UserEntity u where u.username = ?1")
Remove dòng này nếu ko cần thiết e?

2023-03-06 02:23 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +        return toUser(userRepository.save(toUserEntity(user)));
Nếu user này đã tồn tại thì sao e?

2023-03-06 02:23 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +        return toUser(userRepository.save(toUserEntity(user)));
Nếu user khác đã tồn tại thì sao e?

2023-03-06 02:25 UTC, tleviet commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL))
E ko cần dùng `this.` phía trước nhé

2023-03-06 02:29 UTC, tleviet commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PatchMapping("/update/{userId}")
Api này nên dùng PUT hay PATCH e?
cc @voquanghoa

2023-03-06 02:30 UTC, tleviet commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.patch(BASE_URL + "/update/" + userToUpdate.getId()).contentType(MediaType.APPLICATION_JSON).content(new ObjectMapper().writeValueAsString(toUserDTO(use
dòng này hơi dài e, nên format xuống dòng

2023-03-06 02:32 UTC, tleviet commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +        /* This method will perform findById */
xoá dòng này nếu ko cần thiết e?

2023-03-06 02:34 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldCreateUser_Ok() {
Thêm test cho trường hợp user tồn tại e
cc @voquanghoa

2023-03-06 02:34 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        /* Accept any `UserEntity` object */
xoá dòng này nếu ko cần thiết e?

2023-03-06 02:35 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        expected.setId(user.getId());
sao mình `setId()` ở đây e?

2023-03-06 02:38 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public ResponseEntity<Void> deleteById(final @PathVariable UUID userId) {
yep. Dùng void đi

2023-03-06 02:39 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserDTO.java
> +    private UUID roleId;
Cứ để roleId, ví dụ frontend cần hiển thị nó theo dropdown. Do ở đây mình define role không theo enum nên cứ để như thế này là ok.

2023-03-06 02:40 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        expected.setId(user.getId());
Fixed

2023-03-06 02:40 UTC, voquanghoa commented on src/main/java/com/javatemplate/error/UserExistedException.java
> +public class UserExistedException extends DomainException {
Lớp này không cần define, có thể chỉ cần define lớp `BadRequestException` là được. Hoặc nếu define lớp này thì cũng sẽ extend từ `BadRequestException` chứ không phải là `DomainException`

2023-03-06 02:41 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +        return toUser(userRepository.save(toUserEntity(user)));
Cần phải check user không trùng username

2023-03-06 02:42 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +        return toUser(userRepository.save(toUserEntity(user)));
Hàm này nên được khai báo
```java
public User updateUser(final UUID userId, final User user) {
```

2023-03-06 02:43 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PatchMapping("/update/{userId}")
PUT hay PATCH không quan trọng, quan trọng là define HTTP method gì thì logic tương ứng phải implement đúng theo HTTP method đó

- PUT: Update nguyên object
- PATCH: Update theo từng property

2023-03-06 02:45 UTC, voquanghoa commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.patch(BASE_URL + "/update/" + userToUpdate.getId()).contentType(MediaType.APPLICATION_JSON).content(new ObjectMapper().writeValueAsString(toUserDTO(use
Thử cố gắng tạo 1 class TestUtils rồi refactor chỗ này thành 1 hàm để sử dụng xem.

2023-03-06 02:46 UTC, voquanghoa commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldCreateUser_Ok() {
Phần implement có thể unit test cũng phải update

2023-03-06 02:47 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PostMapping("/create")
```suggestion
    @PostMapping
```

Mình sẽ dùng HTTP Method để phân biệt nên việc thêm tên như thế không cần thiết

2023-03-06 02:47 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PatchMapping("/update/{userId}")
```suggestion
    @PatchMapping("{userId}")
```

Xoá phần tên không cần thiết.

2023-03-06 02:48 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public UserDTO updateUser(final @RequestBody UserDTO userDTO,
```suggestion
    public UserDTO update(final @RequestBody UserDTO userDTO,
```

2023-03-06 02:49 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        System.out.println("user" + user.getUsername());
Tập thói quen dùng debugger thay vì log thế này

2023-03-06 02:50 UTC, voquanghoa commented on src/main/java/com/javatemplate/error/UserExistedException.java
> +        super(HttpStatus.CONFLICT, message, args);
Chỗ này để BadRequest được rồi.

2023-03-06 02:52 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("select u from UserEntity u where u.username = ?1")
Do method của mình đã có tên khá rõ ràng và theo chuẩn `findByUsername`, flyway tự nó build được query nên có thể sẽ không cần

2023-03-06 02:52 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +        return toUser(userRepository.save(toUserEntity(user)));
Bên server xử lý rồi

2023-03-06 02:53 UTC, voquanghoa commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.patch(BASE_URL + "/update/" + userToUpdate.getId()).contentType(MediaType.APPLICATION_JSON).content(new ObjectMapper().writeValueAsString(toUserDTO(use
Hoặc tạo 1 base class

2023-03-06 02:53 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @DeleteMapping("/delete/{userId}")
```suggestion
    @DeleteMapping("{userId}")
```

2023-03-06 02:54 UTC, voquanghoa commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        /* This line mean that `userOpt` will Optional of `user`
Comment không quá cần thiết. Bỏ

2023-03-06 02:55 UTC, voquanghoa commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        final Optional<UserEntity> userOpt = Optional.empty();
Bỏ biến tạm đi, không cần

2023-03-06 02:55 UTC, voquanghoa commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        when(userRepository.save(any(UserEntity.class)))
```suggestion
        when(userRepository.save(any()))
```

2023-03-06 02:58 UTC, voquanghoa commented
Chưa mã hoá user nha. Để PR sau cũng được

2023-03-06 04:13 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public ResponseEntity<Void> deleteById(final @PathVariable UUID userId) {
Done

2023-03-06 04:13 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        System.out.println("user" + user.getUsername());
Done

2023-03-06 04:23 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +public class UserController {
em đã thêm rồi a

2023-03-06 04:23 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/error/UserExistedException.java
> +public class UserExistedException extends DomainException {
Fixed

2023-03-06 04:23 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.patch(BASE_URL + "/update/" + userToUpdate.getId()).contentType(MediaType.APPLICATION_JSON).content(new ObjectMapper().writeValueAsString(toUserDTO(use
Fixed. Em sẽ cố tìm thêm tạo 1 hàm sử dụng.

2023-03-06 04:23 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +        /* This method will perform findById */
Fixed

2023-03-06 04:23 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldCreateUser_Ok() {
Added

2023-03-06 04:24 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        expected.setId(user.getId());
Fixed

2023-03-06 04:24 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PostMapping("/create")
Fixed

2023-03-06 04:24 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @PatchMapping("/update/{userId}")
Fixed

2023-03-06 04:24 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public UserDTO updateUser(final @RequestBody UserDTO userDTO,
Fixed

2023-03-06 04:24 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/error/UserExistedException.java
> +        super(HttpStatus.CONFLICT, message, args);
Fixed

2023-03-06 04:25 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserEntity.java
> +    @Column(name = "role_id")
Fixed

2023-03-06 04:25 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @DeleteMapping("/delete/{userId}")
Fixed

2023-03-06 04:25 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        /* This line mean that `userOpt` will Optional of `user`
Removed

2023-03-06 04:25 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        final Optional<UserEntity> userOpt = Optional.empty();
Fixed

2023-03-06 04:25 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        when(userRepository.save(any(UserEntity.class)))
Fixed

2023-03-06 09:35 UTC, tleviet commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @GetMapping("/search")
api này nên search cả firstName, lastName và username lun e nhé!

2023-03-06 15:41 UTC, tleviet commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setUsername(userUpdate.getUsername());
nếu username = null hoặc password = null thì sao e?

2023-03-06 15:41 UTC, tleviet commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        verifyUserAvailable(user);
nếu username = null hoặc password = null thì sao e?

2023-03-06 16:34 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setUsername(userUpdate.getUsername());
Thử suy nghĩ, có trang web nào bắt em nhập mật khẩu mỗi lần muốn thay đổi thông tin cá nhân không

2023-03-07 02:07 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("SELECT u FROM UserEntity u WHERE CONCAT(u.username, u.firstName, u.lastName) LIKE %:name%")
Dạ em muốn kết hợp cả 3 trường vào để tìm kiếm.
Ví dụ em có data:
username = 'nguyenhanhtuan1206'
first_name = 'Nguyen'
last_name = 'Tuan' 

kết quả: nguyenhanhtuan1206NguyenTuan like '%name%'

2023-03-07 02:12 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("SELECT u FROM UserEntity u WHERE CONCAT(u.username, u.firstName, u.lastName) LIKE %:name%")
Làm đơn giản thôi được rồi. Với lại nếu cách trên, anh tìm "Quang Hoà" sẽ không ra tên anh vì khi concat, nó thành "voquanghoaVõ QuangHoà"

2023-03-07 02:31 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserDTOMapper.java
> +                .password(user.getPassword())
No no, mình sẽ không response password về cho client zzz

2023-03-07 02:32 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +    public static Supplier<BadRequestException> supplyInputsDataFailed() {
Đưa nó vào common error đi với hàm là `supplyValidationError()`

2023-03-07 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    public void verifyUserAvailable(final User user) {
Những hàm khai báo chỉ để dùng nội bộ class thì phải để access modifer là private. (Chấp nhận bên unit test không gọi được nó trực tiếp)

2023-03-07 02:37 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    public User findById(final UUID userId) {
Sắp xếp các hàm sao cho những hàm public (quan trọng) ở trên và private (kém quan trọng) ở dưới

2023-03-07 02:38 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        if (userUpdate.getUsername() == null || userUpdate.getPassword() == null) {
Bình thường mình không bắt user phải nhập password khi update thông tin.
Refactor đưa phần validation ra chỗ riêng

2023-03-07 03:55 UTC, nguyenvanman commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        return userStore.findUsersByName(name);
200 với empty list chớ anh Hòa

2023-03-07 03:57 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("SELECT u FROM UserEntity u WHERE CONCAT(u.username, u.firstName, u.lastName) LIKE %:name%")
vậy nếu search `06ng` vẫn ra đúng ko e?

2023-03-07 06:20 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +    public List<User> findByUsernameOrFirstNameOrLastName(final String name) {
Done

2023-03-07 06:21 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        verifyUserAvailable(user);
Fixed

2023-03-07 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserDTOMapper.java
> +                .password(user.getPassword())
Fixed

2023-03-07 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +    public static Supplier<BadRequestException> supplyInputsDataFailed() {
Fixed

2023-03-07 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        return userStore.findUsersByName(name);
Fixed

2023-03-07 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    public void verifyUserAvailable(final User user) {
Fixed

2023-03-07 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    public User findById(final UUID userId) {
Fixed

2023-03-07 06:23 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        if (userUpdate.getUsername() == null || userUpdate.getPassword() == null) {
Added

2023-03-07 06:58 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setUsername(userUpdate.getUsername());
Fixed

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    }
```suggestion
    public UserDTO create(final @RequestBody UserDTO userDTO) {
        return toUserDTO(userService.create(toUser(userDTO)));
    }
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +        return toUserDTO(userService.updateUser(userId, toUser(userDTO)));
```suggestion
        return toUserDTO(userService.update(userId, toUser(userDTO)));
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserDTO.java
> +    private String password;
Có cái field này sẽ làm cho JSON response có field password. Phải bỏ đi luôn, cả field cả value

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +        return () -> new BadRequestException("User %s is already existing", username);
```suggestion
        return () -> new BadRequestException("Username %s has been taken", username);
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +        return () -> new NotFoundException("User %s doesn't existing!", input);
```suggestion
        return () -> new NotFoundException("Username %s could not be found", input);
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyData(final User user, final String message) {
Message cần specific rõ lỗi về field gì

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyUserAvailable(final User user) {
```suggestion
    private void verifyUserAvailable(final String username) {
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyData(final User user, final String message) {
```suggestion
    private void validateUser(final User user) {
```

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setUsername(userUpdate.getUsername());
Hoặc là không cho đổi username. Hoặc là phải đảm bảo username mới chưa được sử dụng

2023-03-07 07:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setEnabled(userUpdate.getEnabled());
Phải handle password nữa

2023-03-07 08:41 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserDTO.java
> +    private String password;
Done

2023-03-07 08:41 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +        return () -> new BadRequestException("User %s is already existing", username);
Done

2023-03-07 08:41 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserError.java
> +        return () -> new NotFoundException("User %s doesn't existing!", input);
Done

2023-03-07 08:42 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyUserAvailable(final User user) {
Done

2023-03-07 08:42 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyData(final User user, final String message) {
Done

2023-03-07 08:42 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setUsername(userUpdate.getUsername());
Done

2023-03-07 08:42 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void verifyData(final User user, final String message) {
Fixed

2023-03-07 08:48 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +        user.setEnabled(userUpdate.getEnabled());
Done

2023-03-07 08:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +        return toUserDTO(userService.updateUser(userId, toUser(userDTO)));
Fixed

2023-03-07 15:05 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        final var expected = userStore.updateUser(toUser(user));
Fixed

2023-03-07 15:05 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        final var userOpt = Optional.of(user);
Fixed

2023-03-07 15:05 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +        assertEquals(expected.size(), userStore.findAll().size());
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserEntityMapperTest.java
> +    void shouldToUser_Ok() {
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +    void shouldUpdateUser_Thrown() {
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +    void shouldFindById_Throw() {
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +    void shouldFindByUsernameOrFirstNameOrLastName_Thrown() {
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserEntity.java
> +@SuperBuilder
Fixed

2023-03-07 15:06 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserEntityMapper.java
> +
Fixed

2023-03-07 15:07 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserDTORequest.java
> +public class UserDTORequest {
Fixed

2023-03-08 10:08 UTC, nguyenvanman requested changes

2023-03-08 10:08 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/user/UserDTOMapper.java
> +                .roleId(user.getRoleId())
Field này có thể không cần trả về

2023-03-08 10:08 UTC, nguyenvanman commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +            user.setUsername(username);
Tên hàm là `verifyUserAvailableUpdate` thì chỉ thực hiện việc verify thôi, không thay đổi thông tin user

2023-03-08 14:04 UTC, tleviet commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +    void shouldCreateUser_Existed() {
test create user với username existing e hả? edit lại method name lun e

2023-03-08 14:04 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldFindById_Empty() {
test này ko cần cũng đc e

2023-03-08 14:04 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldFindByUsernameOrFirstNameOrLastName_Empty() {
test này ko cần cũng dc e

2023-03-09 01:36 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserDTOMapper.java
> +                .roleId(user.getRoleId())
Done

2023-03-09 01:36 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +            user.setUsername(username);
Done

2023-03-09 01:36 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/user/UserServiceTest.java
> +    void shouldCreateUser_Existed() {
Fixed

2023-03-09 01:37 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldFindByUsernameOrFirstNameOrLastName_Empty() {
Removed

2023-03-09 01:37 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/user/UserStoreTest.java
> +    void shouldFindById_Empty() {
Removed

2023-03-09 15:20 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    @Query("select u from UserEntity u where u.username = ?1")
- [ ] Remove dòng này nếu ko cần thiết e?

2023-03-09 15:20 UTC, tleviet commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL))
- [ ] E ko cần dùng this. phía trước nhé

2023-03-10 01:20 UTC, tleviet approved these changes

2023-03-10 01:49 UTC, merged

2023-03-10 02:20 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +@RequestMapping(value = "/api/v1/users")
Bỏ hết mấy ký tự `/` ở đầu

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    @GetMapping("/{userId}")
Bỏ hết mấy ký tự `/` ở đầu

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public UserResponseDTO createUser(final @RequestBody UserRequestDTO userDTO) {
--> create

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        if (username == null || isBlank(username)) {
Hàm isBlank đã cover vụ null nên không cần check ở đây

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +            throw supplyValidationError("Password not be blank").get();
Wrong English grammar

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void updateUserIfNotAvailable(final User user, final String username) {
Tên hàm không thể hiện đúng việc đang làm (Nếu không thể đặt tên tốt hơn thì đừng tạo hàm này)

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void checkIfUsernameAvailable(final String username) {
checkIfUsernameAvailable --> verifyUsernameAvailable

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    List<UserEntity> findByUsernameOrFirstNameOrLastName(final String name);
Name có thể dùng chung chung cho username, firstName, lastName nên có thể đổi tên hàm thành `findByName` vì tên hiện tại hơi dài

2023-03-10 02:36 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/user/UserStore.java
> +    public List<User> findUsersByName(final String name) {
findByName

2023-03-10 02:49 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +@RequestMapping(value = "/api/v1/users")
Cái này cần bỏ luôn hả anh

2023-03-10 02:53 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        if (username == null || isBlank(username)) {
Fixed

2023-03-10 02:53 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserController.java
> +    public UserResponseDTO createUser(final @RequestBody UserRequestDTO userDTO) {
Fixed

2023-03-10 02:53 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +            throw supplyValidationError("Password not be blank").get();
Fixed

2023-03-10 02:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/user/UserService.java
> +    private void checkIfUsernameAvailable(final String username) {
Fixed

2023-03-10 02:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/user/UserRepository.java
> +    List<UserEntity> findByUsernameOrFirstNameOrLastName(final String name);
Fixed