5 crud book
nguyenhoanganhtuan1206/Java-Template pull request #5
Opened 2023-03-06 14:46 UTC by nguyenhoanganhtuan1206

crud for book

2023-03-07 03:52 UTC, nguyenvanman requested changes

2023-03-07 03:52 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @GetMapping("/{bookId}")
```suggestion
    @GetMapping("{bookId}")
```

2023-03-07 03:52 UTC, nguyenvanman commented on src/main/java/com/javatemplate/domain/book/BookError.java
> +    public static Supplier<NotFoundException> supplyUBookNotFound(final UUID bookId) {
UBook là chi rứa?

2023-03-07 03:52 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @GetMapping("/{bookId}")
Sửa cả mấy chỗ khác

2023-03-07 06:58 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @GetMapping("/{bookId}")
Fixed

2023-03-07 16:25 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookDTO.java
> +    private UUID userId;
Bỏ đi @nguyenhoanganhtuan1206

2023-03-07 16:26 UTC, voquanghoa commented on build.gradle
> +    id 'java'
Hạn chế có những thay đổi không liên quan thế này

2023-03-07 16:26 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public BookDTO update(final @RequestBody BookDTO bookDTO,
Đưa id lên trước

2023-03-07 16:27 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookDTO.java
> +    private UUID userId;
Không cần đâu

2023-03-07 16:30 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findBooksByName(final String bookName);
```suggestion
    List<BookEntity> findByNameContainingIgnoreCase(final String name);
```

2023-03-07 16:31 UTC, voquanghoa commented on src/test/java/com/javatemplate/persistent/book/BookStoreTest.java
> +        when(bookRepository.findBooksByName(bookName)).thenReturn(Collections.emptyList());
Import static nếu có thể
```suggestion
        when(bookRepository.findBooksByName(bookName)).thenReturn(emptyList());
```

2023-03-08 06:49 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL + "/" + book.getId()))
Fixed

2023-03-08 06:50 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public BookDTO update(final @RequestBody BookDTO bookDTO,
Fixed

2023-03-08 06:50 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findBooksByName(final String bookName);
Fixed

2023-03-08 06:51 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        verifyData(book, "Create book failed. Please check your inputs");
Fixed

2023-03-08 06:58 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +                        .content(new ObjectMapper().registerModule(new JavaTimeModule()).writeValueAsString(book)))
Fixed

2023-03-08 06:58 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/book/BookStoreTest.java
> +        when(bookRepository.findBooksByName(bookName)).thenReturn(Collections.emptyList());
Fixed

2023-03-08 06:58 UTC, nguyenhoanganhtuan1206 commented on build.gradle
> +    id 'java'
Dạ a

2023-03-08 06:59 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +    void shouldCreate_Thrown() {
Added

2023-03-08 06:59 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +    private void verifyData(final Book book, final String message) {
Fixed

2023-03-08 06:59 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
>  @RequestMapping("api/v1/books")
Em có thêm rồi anh

2023-03-08 10:00 UTC, nguyenvanman requested changes

2023-03-08 10:00 UTC, nguyenvanman commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        final var expected = bookService.update(book.getId(), bookUpdate);
Xem và sửa lại với tất cả các test khác

2023-03-08 14:10 UTC, tleviet commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @Operation(summary = "Find books by name")
book có nhiều fields khác nữa e: author, description, ....

2023-03-08 14:10 UTC, tleviet commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        }
author = null đc ko e?

2023-03-09 15:21 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        final Book book = findById(uuid);
dòng này dùng để kiểm tra có Id không để throw message ra ấy a

2023-03-09 15:45 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @Operation(summary = "Find books by name")
Added : search by author

2023-03-09 15:45 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        final var expected = bookService.update(book.getId(), bookUpdate);
Fixed

2023-03-10 02:32 UTC, tleviet commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @Operation(summary = "Find books by name")
- [ ] search description nữa e nhé

2023-03-10 02:37 UTC, tleviet commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam String input) {
- [ ] search thêm với book description lun e
- [ ] request param `input` có tên biến nào ok hơn ko e 🤔 ?

2023-03-10 06:50 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam String input) {
Fixed

2023-03-12 11:09 UTC, tleviet commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam(name = "q") String searchTerm) {
nên dùng request param với name giống tên biến lun e `searchTerm`

2023-03-12 11:13 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findByNameAuthorDesc(final String searchTerm);
tên method ở đây với `...Desc` dễ nhầm với field sắp xếp như `desc, asc`. E update lại `...Description` lun nhé

2023-03-12 11:14 UTC, tleviet commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +    void shouldFindByName_Ok() throws Exception {
update lại tên method lun e, mình test search cho cả author và description nữa

2023-03-13 00:41 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam(name = "q") String searchTerm) {
Fixed

2023-03-13 00:41 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findByNameAuthorDesc(final String searchTerm);
Added

2023-03-13 00:41 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +    void shouldFindByName_Ok() throws Exception {
Fixed

2023-03-13 00:42 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/persistent/book/BookStoreTest.java
> +    void shouldBooksFindByName_OK() {
Fixed

2023-03-13 00:44 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +    void shouldFindBooksByName_OK() {
Fixed

2023-03-13 09:05 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/book/BookStoreTest.java
> +    void shouldBooksFindByName_OK() {
- [ ] @nguyenhoanganhtuan1206 thấy vẫn method name cũ e?

2023-03-13 09:05 UTC, tleviet commented on src/test/java/com/javatemplate/persistent/book/BookStoreTest.java
> +        when(bookRepository.findByNameAuthorDescription(anyString())).thenReturn(expected);
- [ ] nên input book name hoặc author thay cho `anyString()` e?

2023-03-13 09:05 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    @Query("SELECT b FROM BookEntity b WHERE CONCAT(b.name, b.author, b.description) like %:searchTerm%")
- [ ] e thử improve lại điều kiện search này nhé vì concat nó + chuỗi lại rồi search 🤔

2023-03-13 09:33 UTC, nguyenvanman requested changes

2023-03-13 09:33 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam String searchTerm) {
```suggestion
    public List<BookDTO> search(final @RequestParam String searchTerm) {
```

2023-03-13 09:33 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @GetMapping("/search")
remove /

2023-03-13 09:33 UTC, nguyenvanman commented on src/main/java/com/javatemplate/domain/book/BookError.java
> +        return () -> new BadRequestException("You don't have permission to update this book");
No permission -> forbidden not bad request

2023-03-13 09:33 UTC, nguyenvanman commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +    private void verifyData(final Book book) {
Tên hàm này chung quá, đặt lại tên cụ thể hơn

2023-03-13 09:33 UTC, nguyenvanman commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        assertEquals(actual.getId(), bookUpdate.getId());
Assert thì để expected trước, actual sau, update lại với tất cả các chỗ khác nhé

2023-03-13 09:33 UTC, nguyenvanman commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        assertEquals(actual.getId(), bookUpdate.getId());
assertXxx(expected, actual);

2023-03-13 10:53 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        assertEquals(actual.getId(), bookUpdate.getId());
Fixed

2023-03-13 10:53 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +    private void verifyData(final Book book) {
Fixed

2023-03-13 10:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookError.java
> +        return () -> new BadRequestException("You don't have permission to update this book");
cái này em làm phân quyền mà quên xóa lại anh

2023-03-13 10:55 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    @GetMapping("/search")
Fixed

2023-03-13 10:55 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookDTO> findBooksByName(final @RequestParam String searchTerm) {
Fixed

2023-03-13 10:55 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    @Query("SELECT b FROM BookEntity b WHERE CONCAT(b.name, b.author, b.description) like %:searchTerm%")
Fixed

2023-03-14 04:51 UTC, tleviet approved these changes

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookController.java
> +        return toBookDTOs(bookService.findByNameAuthorDescription(searchTerm));
```suggestion
        return toBookDTOs(bookService.find(searchTerm));
```

find với search là đồng nghĩa nên chỉ dùng 1 thôi

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookDTO.java
> +    private Instant updatedAt;
2 field này quản lý bởi backend và không được truyền từ frontend (chỉ response từ backend --> frontend, không làm ngược lại)

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +                .updatedAt(bookDTO.getUpdatedAt())
Phải bỏ đi

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +                .id(bookDTO.getId())
Cái này không cần

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        if (book.getName() == null) {
Dùng `isBlank` từ StringUtils

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        if (book.getAuthor() == null) {
Dùng `isBlank` từ StringUtils

2023-03-14 07:08 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/book/BookStore.java
> +    public List<Book> findByNameAuthorDescription(final String searchTerm) {
Ở level store với service thì để tên ngắn lại

2023-03-14 07:08 UTC, voquanghoa commented on src/test/java/com/javatemplate/fakes/BookFakes.java
> +                .createdAt(Instant.EPOCH)
```suggestion
                .createdAt(Instant.now())
```

2023-03-14 08:03 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookRequestDTO.java
>      private UUID id;
Mình không để id ở đây. Khi CREATE thì mình không cần id còn khi update thì mình dùng id từ path

2023-03-14 09:28 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookRequestDTO.java
>      private UUID id;
Fixed

2023-03-14 09:28 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/fakes/BookFakes.java
> +                .createdAt(Instant.EPOCH)
Fixed

2023-03-14 09:28 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookStore.java
> +    public List<Book> findByNameAuthorDescription(final String searchTerm) {
Fixed

2023-03-14 09:29 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +                .id(bookDTO.getId())
Fixed

2023-03-14 09:29 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        if (book.getName() == null) {
Fixed

2023-03-14 09:29 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +                .updatedAt(bookDTO.getUpdatedAt())
Removed

2023-03-14 09:29 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookDTO.java
> +    private Instant updatedAt;
Fixed

2023-03-14 09:29 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +        return toBookDTOs(bookService.findByNameAuthorDescription(searchTerm));
Fixed

2023-03-14 11:25 UTC, tleviet commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        verifyBookInformation(book);
- [ ] mình cho phép create duplicate book với name và author ko e?
cc @voquanghoa

2023-03-14 11:25 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/book/BookEntity.java
>      public static final String ID_FIELD = "id";
- [ ] xóa biến này nếu ko dùng e

2023-03-14 11:25 UTC, tleviet commented on src/main/java/com/javatemplate/persistent/book/BookEntity.java
> +    private String image;
field image này values sẽ là gì e? bên FE có thể view đc image này ko e?

2023-03-14 13:20 UTC, voquanghoa commented on src/main/java/com/javatemplate/domain/book/BookService.java
> +        verifyBookInformation(book);
Được

2023-03-15 03:54 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/book/BookEntity.java
> +    private String image;
Được, sẽ là url (mặc dù tên không ok lắm)

2023-03-15 03:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookEntity.java
> +    private String image;
![image](https://user-images.githubusercontent.com/87653000/225202183-b26c0bea-642b-4905-aaf0-03ca6a405322.png)
Dạ em để y vậy nha a

2023-03-15 03:54 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookEntity.java
>      public static final String ID_FIELD = "id";
Fixed

2023-03-15 03:56 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        if (password.length() < 6) {
Lỡ nó null thì sao. dùng hàm `length` trong `StringUtils`

2023-03-15 03:59 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        if (password.length() < 6) {
Fixed

2023-03-15 04:32 UTC, nguyenvanman requested changes

2023-03-15 04:32 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        validateLengthPassword(user.getPassword());
```suggestion
        validatePassword(user.getPassword());
```

2023-03-15 04:32 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +    public static BookResponseDTO toBookDTO(final Book book) {
Sửa tên hàm

2023-03-15 04:32 UTC, nguyenvanman commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +    public static List<BookResponseDTO> toBookDTOs(final List<Book> books) {
Sửa tên hàm

2023-03-15 04:55 UTC, voquanghoa commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +                        .content(requestBody))
Create an abstract class `AbstractControllerTest` and move these code to reuse

2023-03-15 04:56 UTC, voquanghoa commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findByNameAuthorDescription(final String searchTerm);
Rename to `find`

2023-03-15 06:22 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/user/UserValidation.java
> +        validateLengthPassword(user.getPassword());
Fixed

2023-03-15 06:26 UTC, voquanghoa commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookResponseDTO> search(final @RequestParam String searchTerm) {
```suggestion
    public List<BookResponseDTO> find(final @RequestParam String searchTerm) {
```

2023-03-16 00:32 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/BookControllerTest.java
> +                        .content(requestBody))
Added

2023-03-16 00:32 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookController.java
> +    public List<BookResponseDTO> search(final @RequestParam String searchTerm) {
Fixed

2023-03-16 00:32 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +    public static List<BookResponseDTO> toBookDTOs(final List<Book> books) {
Fixed

2023-03-16 00:32 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/persistent/book/BookRepository.java
> +    List<BookEntity> findByNameAuthorDescription(final String searchTerm);
Fixed

2023-03-16 00:33 UTC, nguyenhoanganhtuan1206 commented on src/main/java/com/javatemplate/api/book/BookDTOMapper.java
> +    public static BookResponseDTO toBookDTO(final Book book) {
Fixed

2023-03-16 04:55 UTC, tleviet commented on src/test/java/com/javatemplate/api/book/AbstractControllerTest.java
> +
- [ ] xóa bớt dòng trống e

2023-03-16 04:55 UTC, tleviet commented on src/test/java/com/javatemplate/api/book/AbstractControllerTest.java
> +public abstract class AbstractControllerTest {
nice :heart_eyes:

2023-03-16 04:55 UTC, tleviet commented on src/test/java/com/javatemplate/api/book/AbstractControllerTest.java
> +    public ResultActions post(final String url, final Book book) throws Exception {
- [ ] e check lại param `Book book` nhé: a thấy chỗ api define class khác mà:

```
@PostMapping
public BookResponseDTO create(final @RequestBody BookCreateRequestDTO bookDTO)
```

2023-03-16 04:55 UTC, tleviet commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        verify(bookStore).findById(uuid);
- [ ] thêm dòng trống phía trên e

2023-03-16 07:13 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/domain/book/BookServiceTest.java
> +        verify(bookStore).findById(uuid);
Fixed

2023-03-16 07:15 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/AbstractControllerTest.java
> +    public ResultActions post(final String url, final Book book) throws Exception {
em đổi lại nó thành object rồi ấy anh và chuyển ra ngoài để reuse rồi anh

2023-03-16 07:15 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/book/AbstractControllerTest.java
> +
REMOVED

2023-03-16 09:07 UTC, tleviet commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        get(BASE_URL).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(users.size())).andExpect(jsonPath("$[0].id").value(users.get(0).getId().toString())).andExpect(jsonPath("$[0].u
- [ ] ủa sao code nằm hết trên 1 dòng e hè

2023-03-16 09:38 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/user/UserControllerTest.java
> +        get(BASE_URL).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(users.size())).andExpect(jsonPath("$[0].id").value(users.get(0).getId().toString())).andExpect(jsonPath("$[0].u
Fixed, format IDE bên em ctrl S là nó bị lên dòng ấy anh

2023-03-16 16:07 UTC, voquanghoa approved these changes
Refactor thêm chút ở AbstractControlerTest

2023-03-16 17:25 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/AbstractControllerTest.java
> +        return mockMvc.perform(mockHttpServletRequestBuilder.contentType(MediaType.APPLICATION_JSON));
Fixed

2023-03-16 17:26 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/javatemplate/api/AbstractControllerTest.java
> +        return mockMvc.perform(mockHttpServletRequestBuilder.contentType(MediaType.APPLICATION_JSON));
ADDED

2023-03-16 17:26 UTC, merged